# Setup
title:            WeWork
tagline:          Engineering Blog
url:              https://engineering.wework.com
paginate:         1
baseurl:          /

author:
  name:           WeWork
  email:          careers@wework.com

# Permalinks
permalink:        pretty
relative_permalinks: true

# Syntax highlighting
highlighter:      pygments

sass:
  sass_dir:       _scss
  style:          compressed
